# Generated by Django 4.2.3 on 2023-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_custompayallowance_custompaydeduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='worked_days',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
