# Generated by Django 4.2.3 on 2023-08-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salaryhistory_worked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='due',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='payment_status',
            field=models.CharField(default='nil', max_length=100),
            preserve_default=False,
        ),
    ]
