# Generated by Django 4.2.3 on 2023-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salaryhistory_due_salaryhistory_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='financial_year',
            field=models.CharField(default='2020-2021', max_length=100),
            preserve_default=False,
        ),
    ]
