# Generated by Django 4.2.3 on 2023-08-14 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payroll', '0006_alter_salaryhistory_salary_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryhistory',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='deductions',
        ),
        migrations.CreateModel(
            name='SalaryHistoryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('salary_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salaryhistory')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistoryAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('salary_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salaryhistory')),
            ],
        ),
    ]
