# Generated by Django 4.2.3 on 2023-08-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_remove_salaryhistory_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='due',
            field=models.CharField(default='nil', max_length=100),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='payment_status',
            field=models.CharField(default='nil', max_length=100),
        ),
    ]
