# Generated by Django 4.2.3 on 2023-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_payrollprocessed_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprocessed',
            name='workingdays',
            field=models.CharField(default=28, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
