# Generated by Django 4.2.3 on 2023-07-20 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employeedailyattendance_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='attendance_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
