# Generated by Django 4.2.3 on 2023-07-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employeedailyattendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDailyAttendance',
        ),
    ]
