# Generated by Django 4.2.3 on 2023-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employeedailyattendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, default=models.TimeField(blank=True)),
        ),
    ]
