# Generated by Django 4.2.3 on 2023-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_employeedailyattendance_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedailyattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
