# Generated by Django 4.2.3 on 2023-08-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_employeedailyattendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLogProcessed',
            fields=[
                ('DeviceLogId', models.BigAutoField(primary_key=True, serialize=False)),
                ('DownloadDate', models.DateTimeField(blank=True, null=True)),
                ('DeviceId', models.IntegerField(blank=True, null=True)),
                ('UserId', models.CharField(blank=True, max_length=50, null=True)),
                ('LogDate', models.DateTimeField(blank=True, null=True)),
                ('Direction', models.CharField(blank=True, max_length=255, null=True)),
                ('AttDirection', models.CharField(blank=True, max_length=255, null=True)),
                ('C1', models.CharField(blank=True, max_length=255, null=True)),
                ('C2', models.CharField(blank=True, max_length=255, null=True)),
                ('C3', models.CharField(blank=True, max_length=255, null=True)),
                ('C4', models.CharField(blank=True, max_length=255, null=True)),
                ('C5', models.CharField(blank=True, max_length=255, null=True)),
                ('C6', models.CharField(blank=True, max_length=255, null=True)),
                ('C7', models.CharField(blank=True, max_length=255, null=True)),
                ('WorkCode', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'devicelogs_processed',
                'managed': False,
            },
        ),
    ]
