# Generated by Django 4.2.3 on 2023-08-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_shift_shift_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_shift',
            field=models.CharField(default='Not Assigned', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('shift', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
