# Generated by Django 4.2.3 on 2023-08-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
