# Generated by Django 4.2.3 on 2023-09-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_employee_shift_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamshift',
            old_name='from_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='teamshift',
            name='to_date',
        ),
    ]
