# Generated by Django 4.2.3 on 2023-09-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_from_date_teamshift_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='default_shift',
        ),
    ]
