# Generated by Django 4.2.3 on 2023-09-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_team_default_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
