# Generated by Django 4.2.3 on 2023-09-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_customuser_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamShift',
        ),
    ]
