# Generated by Django 4.2.3 on 2023-09-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_team_teamshift_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamshift',
            old_name='team_id',
            new_name='team',
        ),
    ]
