# Generated by Django 4.2.3 on 2023-09-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_customuser_profile_pic_employeepersonaldetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpWorkInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hr_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_partner_for', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
