# Generated by Django 4.2.3 on 2023-09-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_team_hr_partner_delete_empworkinf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shift',
            new_name='EmployeeShift',
        ),
    ]
