# Generated by Django 4.2.3 on 2023-09-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_shift_employeeshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShiftName', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='teamshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shift'),
        ),
    ]
