# Generated by Django 4.2.3 on 2023-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_shift_alter_teamshift_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
