# Generated by Django 4.2.3 on 2023-09-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_employeepersonaldetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
