# Generated by Django 4.2.3 on 2023-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_employeepersonaldetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
