# Generated by Django 4.2.3 on 2023-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_customuser_device_id_customuser_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='attendance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
