# Generated by Django 4.2.3 on 2023-09-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_employeeshift_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeshift',
            old_name='attendance',
            new_name='attendance_status',
        ),
    ]
