# Generated by Django 4.2.3 on 2023-09-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_remove_customuser_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegeneric',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeegeneric',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='workinf',
            name='employee_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
