# Generated by Django 4.2.3 on 2023-09-27 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_remove_employeegeneric_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='hr_partner',
        ),
        migrations.AddField(
            model_name='workinf',
            name='hr_partner',
            field=models.ForeignKey(default=2228, on_delete=django.db.models.deletion.CASCADE, related_name='hr_partner_for', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
