# Generated by Django 4.2.3 on 2023-09-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_team_hr_partner_workinf_hr_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinf',
            name='employee_work',
            field=models.OneToOneField(blank=True, default=22555, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workinf',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
