# Generated by Django 4.2.3 on 2023-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_workinf_employee_work_alter_workinf_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinf',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
